### ISSUE TITLE
Description under title

### ISSUE THREAD

**Issue by lfarah** [oney/Mixin#1]
<img width="396" alt="screen shot 2017-12-18 at 10 57 17 am" src="https://user-images.githubusercontent.com/6511079/34107138-3e0507a6-e3e2-11e7-94fd-d6636b8b6bf8.png">

Please add a description under the title

**Comment by lfarah** [comment]
Please fix this [before we can approve your PR](https://github.com/vsouza/awesome-ios/pull/2155)

**Comment by oney** [comment]
OK, thanks!
